# PyTorch: Quick learning on 5 Tensor operations

PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab. PyTorch includes “Torch” in the name, acknowledging the prior torch library with the “Py” prefix indicating the Python focus of the new project. Tensors are the basic building blocks in PyTorch and they are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing. 

Below are the 5 tensor functions with examples :
- torch.rand :To construct a randomly initialized matrix
- torch.full : To Creates a tensor of size 'size' filled with 'fill_value'
- torch.reshape : Tensor which is reshaped without changing the data.
- torch.clamp : Clamp all elements in input into the range [ min, max ] and return a resulting tensor:
- torch.mean : Returns the mean value of all elements in the input tensor.

Before we begin, let's install and import PyTorch

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.rand

Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1]

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2775, 0.6186, 0.1041],
        [0.7248, 0.6059, 0.9258],
        [0.5086, 0.1269, 0.3711],
        [0.6266, 0.3455, 0.3591],
        [0.5760, 0.5477, 0.1024]])


This command creates matrix of 5 rows and 3 columns with the data type float

In [4]:
torch.rand(3,3, requires_grad=True)

tensor([[0.1088, 0.6894, 0.3505],
        [0.4766, 0.8803, 0.5728],
        [0.4733, 0.5451, 0.7236]], requires_grad=True)

Parameter requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False

In [5]:
x = torch.rand(4, 2, dtype=torch.long)
print(x)

RuntimeError: ignored

Creating the matrix of 4 rows and 2 columns with un supported data type throws the error

To create a random tensor with specific shape, use torch.rand() function with shape passed as argument to the function. torch.rand() function returns tensor with random values generated in the specified shape.

## Function 2 - torch.full

This function creates a tensor of 'size' with the value mentioned in 'fill_value' The size can be a list or a tuple.

In [8]:
torch.full(size=(4,2), fill_value=6)

tensor([[6, 6],
        [6, 6],
        [6, 6],
        [6, 6]])

Created a tensor of 4 rows and 2 columns filled with value 6

In [9]:
torch.full(size=[2, 2, 2], fill_value=4*6)

tensor([[[24, 24],
         [24, 24]],

        [[24, 24],
         [24, 24]]])

Here the size is mentioned in list format

In [10]:
torch.full(size=[2,1], fill_value='a')

TypeError: ignored

Values in the tensor cannot be a string type

## Function 3 - torch.reshape

Returns a tensor with the same data and number of elements as input, but with the specified shape.

In [18]:
a = torch.tensor([[0, 1], [2, 3]])
print("Before reshape:\n", a)
a = torch.reshape(a, (-1,))
print("After reshape:\n", a)
a.shape

Before reshape:
 tensor([[0, 1],
        [2, 3]])
After reshape:
 tensor([0, 1, 2, 3])


torch.Size([4])

Here '-1' refers to unwinding the tensor to single dimension

In [22]:
b = torch.arange(4.)
print("Before reshape:\n", b.shape)
b = torch.reshape(b, (2, 2))
print("After reshape:\n", b.shape)
b

Before reshape:
 torch.Size([4])
After reshape:
 torch.Size([2, 2])


tensor([[0., 1.],
        [2., 3.]])

Tensor which has shape of (4) reshaped to (2,2)

In [24]:
torch.reshape(b, (2,3))

RuntimeError: ignored

Need to pass proper size input for reshaping

This command is very useful when we work with NN models

## Function 4 - torch.clamp

This function clamps all elements in input into lower-bound of the range (min) , upper-bound of the range (max) and return a resulting tensor. 

In [27]:
a = torch.randn(4)
print(a)
torch.clamp(a, min=-0.5, max=0.7)

tensor([ 0.3203, -1.0588,  1.0739,  0.7409])


tensor([ 0.3203, -0.5000,  0.7000,  0.7000])

clamped all elements in the input tensor 'a' to range [-0.5 to 0.7]

In [28]:
torch.clamp(a, max=0.6)

tensor([ 0.3203, -1.0588,  0.6000,  0.6000])

Clamps all elements in input to be smaller or equal max(0.6).

In [32]:
b=torch.full(size=[4,3], fill_value=8)
print(b)
torch.clamp(b, max=0.6)

tensor([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]])


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

If input is of type FloatTensor or DoubleTensor, args min and max must be real numbers, otherwise they should be integers.

## Function 5 - torch.mean

Returns the mean value of each row of the input tensor in the given dimension dim. If dim is a list of dimensions, reduce over all of them.

If keepdim is True, the output tensor is of the same size as input except in the dimension(s) dim where it is of size 1. Otherwise, dim is squeezed (see torch.squeeze()), resulting in the output tensor having 1 (or len(dim)) fewer dimension(s).

In [36]:
m = torch.randn(2, 3)
print(m)
torch.mean(m)

tensor([[-0.5047, -0.6616, -2.3984],
        [-0.5758, -0.8946, -0.5671]])


tensor(-0.9337)

Here we havn't mentioned any dimension , so result is squeezed to 1 dimension

In [52]:
a = torch.randn(2, 4, 4)
print("original tensor:\n", a)
print(torch.mean(a, 1))
print(torch.mean(a, 2, True))

original tensor:
 tensor([[[ 2.6334, -0.3781, -0.3770,  0.0966],
         [-0.2986,  1.0616,  0.7748,  2.2552],
         [-0.9330,  1.5062, -2.1099,  1.1717],
         [-0.6346, -1.2665, -0.1428,  0.2116]],

        [[ 0.7836,  1.4585, -0.9360, -1.4345],
         [-0.6118, -0.0169, -0.3252, -0.7605],
         [ 1.5772, -0.0893, -0.0554,  1.9793],
         [-0.4636, -1.4632, -0.3768, -1.5658]]])
tensor([[ 0.1918,  0.2308, -0.4637,  0.9338],
        [ 0.3214, -0.0277, -0.4233, -0.4454]])
tensor([[[ 0.4937],
         [ 0.9483],
         [-0.0912],
         [-0.4580]],

        [[-0.0321],
         [-0.4286],
         [ 0.8530],
         [-0.9673]]])


Here in first output dimension is passed so result size is 4 columns. And in second output, 'keepdim' is set to True, so size is [2, 4,1] .

In [53]:
torch.mean(a, 4, True)

IndexError: ignored

We need to be careful while passing the dimension , shouldnot be out of range.

## Conclusion

we saw the working of five simple and useful functions available in PyTorch.

## Reference Links
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html